### ISSUE TITLE
Chapter 9 downloads

### ISSUE THREAD

**Issue by learning2cde** [PacktPublishing/iOS-13-Programming-for-Beginners#1]
I was trying to download the file for chapter 9 (Assets.xcassets) and when I tried all of it at once it didn't work it just sends a single file. Then I downloaded each document individually and saved it in a folder named the same as the one on the website, but as I went through the chapter I found out that they didn't download, it's still connecting to the github page. So my question is, do I have to go into each file copy and paste each page or picture and save them? Thank you for your time

<img width="403" alt="Screen Shot 2020-05-28 at 4 32 34 PM" src="https://user-images.githubusercontent.com/66095667/83204674-40a7cf00-a101-11ea-87cb-aa3a721234b4.png">

**Comment by aberg619** [comment]
Go to https://github.com/PacktPublishing/iOS-13-Programming-for-Beginners and clone it. You will get all the files including chapter 9.

**Comment by myibookmoe** [comment]
My thanks to @aberg619 for his reply. He is correct.

You can see the steps on how to download the files here: https://ios13programmingpacktpub.blogspot.com/2020/04/how-to-download-code-bundle-for-book-on.html
